### ISSUE TITLE
mobile & tablet support

### ISSUE THREAD

**Issue by muveso** [rizerphe/obsidian-companion#12]
is this possible? right now I cant enable the plugin. we can trigger the complation with commands. it is impossible to use "tab" on mobile 😅
@rizerphe 
![image](https://github.com/rizerphe/obsidian-companion/assets/94571116/0ff1366b-1b20-4174-8b71-674ee152e9e9)

**Comment by rizerphe** [comment]
So far, I have yet to put any thought into mobile support. Considering you can now trigger completion with commands, I will add it soon; thank you!

**Comment by rizerphe** [comment]
Sorry for making you wait, and thank you! Just added mobile support. If you have any further feedback, don't hesitate to let me know!
