### ISSUE TITLE
Rare limit management

### ISSUE THREAD

**Issue by Fifof-hup** [rizerphe/obsidian-companion#14]
Hi @rizerphe 
I'm surprised because I get a "rare limit" issue and I just create an Open AI / chat GPT account. 
Have you ever face something like that? 
thanks a lot 
Fifof

**Comment by rizerphe** [comment]
Yes, this does happen a lot, especially with free OpenAI accounts - see #8 . ChatGPT is meant to only give you a few responses a minute, so OpenAI set a hard limit. This is enough for pretty much every chat application out there, but in this case we're not using ChatGPT for chat but for autocompletion. You have two options here - either adding a credit card to your OpenAI account, or adding a fallback model - AI21's Jurassic models or goose.ai's ones work well enough, you can do this by creating a preset in the plugin settings and setting it as the fallback. Unfortunately, there's not much I can do - even though ChatGPT definitely gives the best results, it's not ChatGPT's intended purpose, so these rate limits are not surprising.

**Comment by localjo** [comment]
I think there's a bug here. I have a paid OpenAI account, and I just installed the Companion plugin, added an API key, and typed one sentence. I didn't get a single suggestion, but I immediately got an error that says "Rate limit exceeded". Could it be that maybe the plugin is requesting a completion on every single keystroke? Perhaps it needs to wait for there to be a delay in typing of a few seconds before querying the API for a completion.
