### ISSUE TITLE
Hot key for accepting all text?

### ISSUE THREAD

**Issue by TheAllenChou** [rizerphe/obsidian-companion#2]
Hi:

First of all, thanks for this plugin. I'm looking for a similar great experience I have with the GitHub Copilot plugin in VS Code, and this plugin comes close. Just one minor thing though, pressing Tab only accepts the next word. Is there a way to have a separate mode, or even an option to replace the default Tab behavior to accept all the text? That would be more consistent with my experience with GitHub Copilot and I don't really like pressing Tab a bunch of time just to accept all the suggest text.

**Comment by rizerphe** [comment]
Thank you! This is planned, I just don't have time to implement it right now. Expect it next week or so.

**Comment by rizerphe** [comment]
Thanks again for your suggestion. It took a bit longer; sorry about that. Just added different completion modes; you can change them in the plugin settings. If you have any further feedback or notice any issues, please don't hesitate to let me know!

**Comment by TheAllenChou** [comment]
Amazing.
Thanks for the update.

--

*Ming-Lun "Allen" Chou*
http://allenchou.net
