### ISSUE TITLE
The accept short cut (Tab) dont work if the vim keys are enabled

### ISSUE THREAD

**Issue by ecruzolivera** [rizerphe/obsidian-companion#3]
Hi all, thanks for building this plugin, is very cool. 

Any chance that the accept command key can be customizable, I use Obsidian in vim mode and this plugin doesn't work with that.

**Comment by ecruzolivera** [comment]
dont work on lists but it works on paragraphs

**Comment by DimitrisMilonopoulos** [comment]
you can use ctrl + space for lists

**Comment by rizerphe** [comment]
I'm working on it, thank you.

**Comment by rizerphe** [comment]
Thanks again! I have added the ability to create your own accept shortcut by either specifying a new CodeMirror one or adding a keybind to the "accept completion" command (`Settings > Hotkeys`). I'm not closing this issue yet though as there is more work to do - the behavior of the tab key is modified even if you disable the CodeMirror keybind, and I haven't tested the behaviour of CodeMirror with vim mode at all.

**Comment by rizerphe** [comment]
Now, the plugin should entirely disable the keymap modifications if the shortcut is disabled in the settings, and it shouldn't suggest completions at all in normal mode with vim keybindings while working as usual in insert mode. If you have any further feedback, don't hesitate to let me know!
