### ISSUE TITLE
THANK YOU, THIS IS AMAZING!

### ISSUE THREAD

**Issue by Bluemoondragon07** [rizerphe/obsidian-companion#4]
Thank you so much for this plug-in, it's amazing! I've only been using it for a day, and WOW--it makes writing so much easier! And the AI is surprisingly much better than any other AI-based plug-in I've tried; I've found it refining responses not just based on the context of the current note, but on multiple notes throughout my vault. It's crazy! And I love it!

Seriously, this plug-in is--WOW. This plug-in is such a blessing! Again, thank you so much, I have no words other than, WOW THIS IS AMAZING.

**Comment by andreiRS** [comment]
@rizerphe Thank you also from my side! Was looking for so much time, for this kind of functionality!

Do you have a https://www.buymeacoffee.com account or other way we can show our appreciation for your effort?

**Comment by ReinerKnudsen** [comment]
Give us your buy-me-a-coffee-account, please 😀

**Comment by rizerphe** [comment]
Thank you so much! I'm way beyond just happy that you liked it, and really appreciate your interest in supporting my work!

@Bluemoondragon07 , a bit of a correction - the plugin does not use more than one note for context. I am thinking of adding that functionality, and I have some ideas on how to do that, but it still needs to be added.

I have made a buymeacoffee account, you can find the link in the README or [here](https://bmc.link/rizerphe)

**Comment by andreiRS** [comment]
Thanks @rizerphe. Just used it. Thanks again for everything!

**Comment by ReinerKnudsen** [comment]
You got some more coffee. Especially happy to support someone from the Ukraine! You got this!
