### ISSUE TITLE
Add a few more keywords into the description

### ISSUE THREAD

**Issue by rhusiev** [rizerphe/obsidian-companion#5]
When searching the obsidian store using "companion" or "copilot" keywords, the plugin appears. However, when searching for "complete", "completion" or "autocomplete", it doesn't.

I suggest adding these keywords to be more findable.

**Comment by rizerphe** [comment]
Thank you! Just changed the description of the plugin, it should now be a lot easier to find. If you have any further feedback, don't hesitate to let me know!
