### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by ReinerKnudsen** [rizerphe/obsidian-companion#6]
Hi, I downloaded the package and unzipped it into the .plugins folder. When I restart Obsidian I can see the plugin, but I can't activate it. It says "Failed to load plugin". I know that this description isn't very specific but I don't know where to find more detailed debug information. 
Anything I can try or look for?

**Comment by rizerphe** [comment]
You can find more details by opening the console (ctrl/command + shift + i); if there are any errors there, seeing them would be very useful. The plugin is now available as "Companion" from the Obsidian community plugin store, too. Does it work when you install it from there?

**Comment by ReinerKnudsen** [comment]
That worked perfectly. thanks. Now I get a 429 error when the request to Open-AI goes out. I use "OpenAI ChatGPT" as provider and verified the secret key is ok.
