### ISSUE TITLE
Bing API

### ISSUE THREAD

**Issue by huachuman** [rizerphe/obsidian-companion#7]
There's a repo with a Bing chat api right now. Any chance of getting this working, or some idea of how to make it happen?

https://github.com/tuhinpal/bingchat-api

**Comment by rizerphe** [comment]
This is not an official implementation; bing does not provide an API. This project is just web scraping, making it unreliable and meaning that by using it you're potentially violating bing's TOS. I'm not considering supporting this.

**Comment by huachuman** [comment]
Lol ok. Guess I'll have to find someone else then... or do it myself.
