### ISSUE TITLE
How to set parameters values of max_token, temperature and top_p ? 

### ISSUE THREAD

**Issue by laurentbarbier** [rizerphe/obsidian-companion#9]
Hello,

Thanks a lot for your useful work.

Do you plan to make the ChatGPT settings max_token, temperature and top_p possible ? 
Would it be savable into multiple Presets ?

Take care,

**Comment by rizerphe** [comment]
Thank you! Changing those settings is possible, and I just removed the visual bug that made it look like they're not savable into presets - they are, the settings were just not displaying properly. Should be working now. If you have any further feedback, don't hesitate to let me know!
